/*
 * SPDX-FileCopyrightText: 2025 Samuel Wu
 *
 * SPDX-License-Identifier: MIT
 *
 * The following code is generated by ChatGPT with modifications.
 *
 * An object oriented implementation can be found at
 * https://github.com/Kraktoos/Python-Elo-System.
 */

import type { Ratings } from "./schemas";

export type EloSystem = Record<string, Ratings>;
export type Score = 0.0 | 0.5 | 1.0;
export type MatchResult = "win" | "loss" | "draw";

export const DEFAULT_RATINGS = {
  draws: 0,
  elo: 1000,
  losses: 0,
  wins: 0,
};

const DEFAULT_K_FACTOR = 32;

const calculateExpectedScore = (ratingA: number, ratingB: number) =>
  1 / (1 + 10 ** ((ratingB - ratingA) / 400));

function updateStats(
  system: EloSystem,
  player: string,
  rating: number,
  result: MatchResult,
) {
  const current = system[player];

  return {
    ...current,
    draws: current.draws + (result === "draw" ? 1 : 0),
    elo: rating,
    losses: current.losses + (result === "loss" ? 1 : 0),
    wins: current.wins + (result === "win" ? 1 : 0),
  };
}

export function recordMatch(
  system: EloSystem,
  playerA: string,
  playerB: string,
  score: Score,
  kFactor = DEFAULT_K_FACTOR,
) {
  if (!system[playerA]) {
    throw new Error(`Player '${playerA}' does not exist in the system.`);
  }

  if (!system[playerB]) {
    throw new Error(`Player '${playerB}' does not exist in the system.`);
  }

  const ratingA = system[playerA].elo;
  const ratingB = system[playerB].elo;

  const expectedA = calculateExpectedScore(ratingA, ratingB);
  const expectedB = 1 - expectedA;

  const newRatingA = Math.round(ratingA + kFactor * (score - expectedA));
  const newRatingB = Math.round(ratingB + kFactor * (1 - score - expectedB));

  const result = score === 1 ? "win" : score === 0 ? "loss" : "draw";

  return {
    ...system,
    [playerA]: updateStats(system, playerA, newRatingA, result),
    [playerB]: updateStats(
      system,
      playerB,
      newRatingB,
      result === "win" ? "loss" : result === "loss" ? "win" : result,
    ),
  };
}

export function shuffleArray<T>(array: readonly T[]): readonly T[] {
  const result = array.slice();
  let i = result.length;

  while (i > 1) {
    i--;
    const j = Math.floor(Math.random() * i);
    [result[i], result[j]] = [result[j], result[i]];
  }

  return result as readonly T[];
}
